Console.WriteLine("CAPACITACION GBM!");
Console.WriteLine("CAPACITACION GBM15!");
Console.WriteLine("CAPACITACION GBM232!");
Console.WriteLine("CAPACITACION GBM1!");
Console.WriteLine("CAPACITACION GBM6!");
Console.WriteLine("CAPACITACION GBM16!");
Console.WriteLine("CAPACITACION GBM62!");
Console.WriteLine("CAPACITACION GBM63!");
Console.WriteLine("CAPACITACION GBM77!");